# zutun:
#Funktion zur generation von Seitennamen frü die Was fragen und die HAuptseite.

import random

import json

GrundwortschatzA = [
    'aber',
    'abgeb',
    'abhol',
    'abschluß',
    'achtung',
    'adress',
    'ahnung,',
    'aktiv',
    'aktuell',
    'all',
    'allein',
    'alt',
    'alter',
    'ampel',
    'anbiet',
    'angebot',
    'änder',
    'ändert',
    'anders',
    'anfang',
    'angst',
    'ankomm',
    'ankunft',
    'anmach',
    'angemacht',
    'anmelden',
    'anmeldung',
    'anruf',
    'anrufbeantworter',
    'anschluss',
    'ansehn',
    'antwort',
    'anzeigen',
    'anzug',
    'apfel',
    'apotheken',
    'apparat',
    'arbeit',
    'arbeitslos',
    'ärger',
    'arm',
    'armen',
    'artikel',
    'auch',
    'auf',
    'aufhör',
    'aufmach',
    'aufpass',
    'aufräume',
    'aufreg',
    'aufsteh',
    'aufzug',
    'auge',
    'aus',
    'ausbildung',
    'ausflug',
    'ausfüll',
    'ausgang',
    'ausgeb',
    'ausgeh',
    'auskunft',
    'ausland',
    'ausmach',
    'auspack',
    'ausruh',
    'aussehen',
    'außer',
    'außerdem',
    'außerhalb',
    'aussprech',
    'aussteig',
    'ausstellung',
    'austrag',
    'ausweis',
    'auto',
    'autobahn',
    'automat',
    'automatisch',
]

GrundwortschatzB = [
    "baby",
    "babysitter",
    "back",
    "bäckerei",
    "bad",
    "baden",
    "bahn",
    "bahnhof",
    "bahnsteig",
    "bald",
    "balkon",
    "ball",
    "banane",
    "band",
    "bank",
    "sitzbank",
    "bar",
    "basketball",
    "bastel",
    "bauch",
    "bauen",
    "baum",
    "baustelle",
    "bedank",
    "bedeuten",
    "bedeutung",
    "beeil",
    "beenden",
    "beginnen",
    "beginn",
    "begründen",
    "beide",
    "bein",
    "bekannt",
    "bekannte",
    "bekommen",
    "bekomm",
    "beliebt",
    "benutzen",
    "bequem",
    "beraten",
    "berg",
    "berichten",
    "bericht",
    "beruf",
    "berühmt",
    "bescheid",
    "beschreiben",
    "beschreibung",
    "beschweren",
    "besetzt",
    "besichtigen",
    "besonders",
    "bestätigungen",
    "bestandenen",
    "bestellen",
    "besuch",
    "besuchen",
    "bett",
    "bewerben",
    "Bewerbung",
    "bewölkt",
    "bezahlen",
    "bibliothek",
    "bier",
    "bild",
    "billig",
    "birne",
    "bisschen",
    "bitten",
    "bitte",
    "beten",
    "bitter",
    "blatt",
    "bleiben",
    "bleistift",
    "blöd",
    "blog",
    "blond",
    "blume",
    "bluse",
    "bohne",
    "böse",
    "braten",
    "brauchen",
    "brief",
    "briefmarke",
    "brille",
    "bringen",
    "brot",
    "brötchen",
    "brücke",
    "buch",
    "buchen",
    "buchstabe",
    "buchstabieren",
    "bunt",
    "büro",
    "bus",
    "butter",
]

GrundwortschatzC = [
    "café",
    "cafeteria",
    "chatten",
    "chef",
    "chefin",
    "klub",
    "comic",
    "computer",
    "creme",
]

GrundwortschatzD = [
    "damals",
    "dame",
    "daneben",
    "dank",
    "datei",
    "datum",
    "dauer",
    "denken",
    "denn",
    "deshalb",
    "deutlich",
    "ding",
    "direkt",
    "disko",
    "diskutieren",
    "doppelzimmer",
    "dorf",
    "dorther",
    "dorthin",
    "dort",
    "draußen",
    "dringend",
    "drinnen",
    "drüben",
    "drücken",
    "drucker",
    "dumm",
    "dunkel",
    "dünn",
    "durch",
    "dürfen",
    "durst",
    "dusche",
    "duschen",
]

GrundwortschatzE = [
    "ebook",
    "echt",
    "ecke",
    "egal",
    "ehefrau",
    "ehemann",
    "ehepartner",
    "ei",
    "eigen",
    "eigentlich",
    "eilig",
    "einfach",
    "eingang",
    "einig",
    "einkaufen",
    "einkauf",
    "einkaufszentrum",
    "einladen",
    "einladung",
    "einmal",
    "einpacken",
    "einsteigen",
    "eintragen",
    "eintritt",
    "einverstanden",
    "einzel",
    "einziehen",
    "eis",
    "email",
    "empfänger",
    "empfehlen",
    "ende",
    "endlich",
    "eng",
    "entschuldigen",
    "entschuldigung",
    "erdgeschoss",
    "erfahrung",
    "erinnern",
    "erkälten",
    "erklären",
    "erlauben",
    "erlaubnis",
    "ermäßigung",
    "erreichen",
    "erwachsene",
    "erzählen",
    "essen",
]

GrundwortschatzF = [
    "fach",
    "fahren",
    "fahrkarte",
    "fahrplan",
    "fahrrad",
    "fallen",
    "falsch",
    "familie",
    "fan",
    "fantastisch",
    "farbe",
    "fast",
    "faul",
    "fehlen",
    "fehler",
    "feier",
    "feierabend",
    "feiertag",
    "feiern",
    "fenster",
    "ferien",
    "fernsehen",
    "fernseher",
    "fertig",
    "fest",
    "festival",
    "fett",
    "fieber",
    "film",
    "finden",
    "firma",
    "fisch",
    "fit",
    "flasche",
    "fleisch",
    "fleißig",
    "fliegen",
    "fliegt",
    "flohmarkt",
    "flug",
    "flughafen",
    "flugzeug",
    "fluss",
    "formular",
    "fotoapparat",
    "fotografieren",
    "foto",
    "frage",
    "fragen",
    "frau",
    "frei",
    "freiwillig",
    "freizeit",
    "fremd",
    "freuen",
    "freund",
    "freundinnen",
    "frisch",
    "froh",
    "früh",
    "frühstück",
    "fühlen",
    "führer",
    "führerschein",
    "führung",
    "fundsachen",
    "furchtbar",
    "fuß",
    "fußball",
]

GrundwortschatzG = [
    "gabel",
    "ganz",
    "garage",
    "garten",
    "gast",
    "geben",
    "geboren",
    "geehrt",
    "gefährlich",
    "gegen",
    "gegenteil",
    "gegenüber",
    "gehalt",
    "gehen",
    "gehören",
    "geld",
    "geldbörse",
    "gemüse",
    "genau",
    "genug",
    "gepäck",
    "gerade",
    "geradeaus",
    "gerät",
    "gericht",
    "geschäft",
    "geschenk",
    "geschichte",
    "geschirr",
    "gesicht",
    "gespräch",
    "gestern",
    "gesund",
    "gesundheit",
    "getränk",
    "gewinnen",
    "gewitter",
    "gitarre",
    "glas",
    "glauben",
    "gleich",
    "gleis",
    "glück",
    "glücklich",
    "glückwunsch",
    "gratulieren",
    "grillen",
    "grippe",
    "groß",
    "größe",
    "gruppe",
    "gruß",
    "gültig",
    "günstig",
    "gut",
]

GrundwortschatzH = [
    "haar",
    "haben",
    "hähnchen",
    "halle",
    "hallo",
    "hals",
    "halten",
    "haltestelle",
    "hamburger",
    "hand",
    "handtuch",
    "handy",
    "hängen",
    "hart",
    "hässlich",
    "hauptstadt",
    "haus",
    "haushalt",
    "heft",
    "heimat",
    "heiraten",
    "heiß",
    "heizung",
    "helfen",
    "hell",
    "hemd",
    "heraus",
    "herein",
    "herd",
    "herr",
    "herstellen",
    "herunterladen",
    "heute",
    "hier",
    "hilfe",
    "himmel",
    "hinten",
    "hinter",
    "hobby",
    "hoch",
    "hochzeit",
    "hoffen",
    "hoffentlich",
    "holen",
    "homepage",
    "hören",
    "hose",
    "hotel",
    "hund",
    "hunger",
    "husten",
]

GrundwortschatzI = [
    "idee",
    "immer",
    "information",
    "informieren",
    "insel",
    "instrument",
    "interesse",
    "interessieren",
    "international",
    "internet",
    "interview",
]

GrundwortschatzJ = [
    "jacke",
    "jeans",
    "jeder",
    "jemand",
    "jetzt",
    "job",
    "joggen",
    "jugend",
    "jugendherberge",
    "jugendliche",
    "jung",
    "junge",
]

GrundwortschatzK = [
    "kaffee",
    "kalender",
    "kalt",
    "kamera",
    "kaputt",
    "karte",
    "kartoffel",
    "käse",
    "kasse",
    "katze",
    "kaufen",
    "kaufhaus",
    "keller",
    "kennen",
    "kennenlernen",
    "kenntnis",
    "kette",
    "kind",
    "Kindergarten",
    "kino",
    "kiosk",
    "kirche",
    "klappen",
    "klar",
    "klavier",
    "kleid",
    "kleidung",
    "klein",
    "klug",
    "kochen",
    "koffer",
    "kollege",
    "kollegin",
    "komisch",
    "kommen",
    "können",
    "kontakt",
    "konto",
    "kontrollieren",
    "konzert",
    "kopf",
    "körper",
    "kosmetik",
    "kosten",
    "kostenlos",
    "krank",
    "kranken",
    "krankenhaushaus",
    "krankenkasse",
    "krankheit",
    "kredit",
    "kreuzung",
    "kriegen",
    "krimi",
    "küche",
    "kuchen",
    "kühl",
    "kühlschrank",
    "kultur",
    "kümmern",
    "kunde",
    "kundin",
    "kündigen",
    "kunst",
    "kurs",
    "kurz",
]

GrundwortschatzL = [
    "lachen",
    "laden",
    "lampe",
    "land",
    "landschaft",
    "lang",
    "lange",
    "langsam",
    "langweilig",
    "laptop",
    "lassen",
    "laufen",
    "laut",
    "leben",
    "lebensmittel",
    "leer",
    "legen",
    "leicht",
    "leider",
    "leihen",
    "leise",
    "lernen",
    "lesen",
    "letzt",
    "leute",
    "licht",
    "liebe",
    "lieben",
    "liebling",
    "lied",
    "liefern",
    "liegen",
    "link",
    "löffel",
    "lokal",
    "lüge",
    "lügen",
    "lust",
    "lustig",
]

GrundwortschatzM = [
    "machen",
    "mädchen",
    "magen",
    "mailbox",
    "mal",
    "malen",
    "manchmal",
    "mann",
    "männlich",
    "mannschaft",
    "mantel",
    "markt",
    "maschine",
    "medikament",
    "meer",
    "meinen",
    "meinung",
    "meist",
    "menge",
    "mensch",
    "merken",
    "messe",
    "messer",
    "miete",
    "mieten",
    "milch",
    "mindest",
    "mineralwasser",
    "mit",
    "mitbringen",
    "mitkommen",
    "mitmachen",
    "mitnehmen",
    "mitspielen",
    "mitarbeiter",
    "mittagessen",
    "mitte",
    "mittel",
    "möbel",
    "mobiltelefon",
    "möchten",
    "mode",
    "moder",
    "mögen",
    "möglich",
    "moment",
    "morgen",
    "motor",
    "motorroller",
    "müde",
    "müll",
    "mund",
    "museum",
    "musik",
    "müssen",
    "mütze",
]

GrundwortschatzN = [
    "nachbar",
    "nachbarinnen",
    "nachricht",
    "nächste",
    "Nähe",
    "name",
    "nass",
    "natur",
    "natürlich",
    "neben",
    "nebenan",
    "neblig",
    "nehmen",
    "nennen",
    "nervös",
    "nett",
    "neu",
    "nichts",
    "nie",
    "niemand",
    "nirgends",
    "noch",
    "normal",
    "note",
    "notieren",
    "notiz",
    "notwendig",
    "nudel",
    "nummer",
    "nur",
    "nützlich",
]

GrundwortschatzO = [
    "oben",
    "obst",
    "oder",
    "offen",
    "öffnen",
    "oft",
    "ohne",
    "ohr",
    "öl",
    "online",
    "orange",
    "ordnung",
    "organisieren",
    "ort",
]

GrundwortschatzP = [
    "paar",
    "packen",
    "paket",
    "papier",
    "parfüm",
    "park",
    "parken",
    "partner",
    "partnerinnen",
    "party",
    "pass",
    "passen",
    "passieren",
    "passwort",
    "pause",
    "person",
    "pferd",
    "pflanze",
    "pizza",
    "plakat",
    "plan",
    "planen",
    "platz",
    "plötzlich",
    "polizei",
    "portion",
    "post",
    "poster",
    "postkarte",
    "postleitzahl",
    "praktikum",
    "praktisch",
    "praxis",
    "preis",
    "preiswert",
    "privat",
    "pro",
    "probieren",
    "problem",
    "produkt",
    "programm",
    "projekt",
    "prospekt",
    "prüfen",
    "prüfung",
    "pullover",
    "pünktlich",
    "putzen",
    "geputzt",
]

GrundwortschatzQ = [
    "qualität",
    "quiz",
]

GrundwortschatzR = [
    "radio",
    "raten",
    "fathaus",
    "rätsel",
    "rauchen",
    "raum",
    "rechnen",
    "rechnung",
    "recht",
    "reden",
    "regen",
    "regnen",
    "reich",
    "reifen",
    "reihe",
    "reinigung",
    "reis",
    "reise",
    "reisebüro",
    "reiseführer",
    "reisen",
    "reiten",
    "renovieren",
    "rentner",
    "rentnerin",
    "reparatur",
    "reparieren",
    "reservieren",
    "rest",
    "restaurant",
    "rezept",
    "rezeption",
    "richtig",
    "riechen",
    "rind",
    "ring",
    "rock",
    "romantisch",
    "rose",
    "rücken",
    "rucksack",
    "ruhe",
    "ruhig",
    "rund",
    "rundgang",
]

GrundwortschatzS = [
    "sache",
    "saft",
    "sagen",
    "salat",
    "salz",
    "sammeln",
    "satz",
    "sauber",
    "sauer",
    "schade",
    "schädlich",
    "schaffen",
    "schalter",
    "scharf",
    "scheinen",
    "schenken",
    "schenkt",
    "schere",
    "schicken",
    "schiff",
    "schild",
    "schimpfen",
    "schirm",
    "schlafen",
    "schlafzimmer",
    "schlecht",
    "schließen",
    "schlimm",
    "schloss",
    "schluss",
    "schlüssel",
    "schmecken",
    "schmerz",
    "schmutzig",
    "schnee",
    "schneiden",
    "schneien",
    "schnell",
    "schokolade",
    "schon",
    "schön",
    "schrank",
    "schrecklich",
    "schreiben",
    "schriftlich",
    "schuh",
    "schule",
    "schüler",
    "schülerinnen",
    "schwanger",
    "schwein",
    "schwer",
    "schwierig",
    "schwimmbad",
    "schwimmen",
    "see",
    "sehen",
    "sehenswürdigkeit",
    "seife",
    "sein",
    "seite",
    "selbst",
    "sendung",
    "service",
    "setzen",
    "sicher",
    "singen",
    "situation",
    "sitzen",
    "sofa",
    "sofort",
    "sogar",
    "sollen",
    "sonne",
    "sonnig",
    "sonst",
    "spannend",
    "sparen",
    "spaß",
    "spät",
    "später",
    "spazieren",
    "spaziergang",
    "speicher",
    "speisekarte",
    "spiel",
    "spielen",
    "sport",
    "sportlich",
    "sportplatz",
    "sprache",
    "sprechen",
    "sprechstunde",
    "stadt",
    "stadtplan",
    "star",
    "stark",
    "stattfinden",
    "findet statt",
    "stehen",
    "stelle",
    "stellen",
    "sterben",
    "stiefel",
    "stift",
    "stipendium",
    "stock",
    "stockwerk",
    "stören",
    "strand",
    "straße",
    "straßenbahn",
    "streiten",
    "streng",
    "stress",
    "stressig",
    "stück",
    "student",
    "studentinnen",
    "studieren",
    "studium",
    "stuhl",
    "suchen",
    "supermarkt",
    "suppe",
    "surfen",
    "süß",
    "süßigkeiten",
    "sympathisch",
]

GrundwortschatzT = [
    "tablet",
    "tablette",
    "tafel",
    "tanzen",
    "tasche",
    "taschengeld",
    "tasse",
    "tauschen",
    "taxi",
    "team",
    "tee",
    "teilen",
    "teilnehmen",
    "telefon",
    "telefonieren",
    "teller",
    "tennis",
    "termin",
    "teuer",
    "text",
    "theater",
    "thema",
    "ticket",
    "tief",
    "Tier",
    "tipp",
    "tisch",
    "titel",
    "toilette",
    "toll",
    "tomate",
    "topf",
    "torte",
    "tot",
    "total",
    "tour",
    "tourist",
    "touristinnen",
    "tragen",
    "trainieren",
    "training",
    "traum",
    "träumen",
    "traurig",
    "treffen",
    "treppe",
    "trinken",
    "trocken",
    "tschüs",
    "t-Shirt",
    "tun",
    "Tür",
    "typisch",
]

GrundwortschatzU = [
    "üben",
    "über",
    "überall",
    "übermorgen",
    "übernachten",
    "übersetzen",
    "übersetzung",
    "überweisen",
    "uhr",
    "umsteigen",
    "umziehen",
    "umzug",
    "unbedingt",
    "unfall",
    "universität",
    "unter",
    "unterhalten",
    "unterkunft",
    "unternehmen",
    "unterricht",
    "unterschied",
    "unterschreiben",
    "unterschrift",
    "untersuchen",
    "unterwegs",
]

GrundwortschatzV = [
    "verabreden",
    "veranstaltung",
    "verbieten",
    "verboten",
    "verdienen",
    "verein",
    "vereinbaren",
    "vergessen",
    "vergleichen",
    "verkaufen",
    "verkehr",
    "verletzen",
    "verlieben",
    "verlieren",
    "verloren",
    "vermieten",
    "vermieter",
    "vermieterinnen",
    "verpassen",
    "verreisen",
    "verschieben",
    "verschoben",
    "verschieden",
    "verspätung",
    "verstehen",
    "versuchen",
    "vertrag",
    "vielleicht",
    "vogel",
    "volleyball",
    "vorbereiten",
    "vorgestern",
    "vorname",
    "vorschlag",
    "vorsichtig",
    "vorstellen",
    "vorwärts",
]

GrundwortschatzW = [
    "wach",
    "wagen",
    "wählen",
    "wahr",
    "wahrscheinlich",
    "wald",
    "wandern",
    "warm",
    "warten",
    "warum",
    "wäsche",
    "waschen",
    "wasser",
    "webseite",
    "wechseln",
    "wecken",
    "weg",
    "wegbringen",
    "wegfahren",
    "weggehen",
    "weglaufen",
    "wegmachen",
    "wegnehmen",
    "wegwerfen",
    "wegen",
    "wehtun",
    "weh",
    "weiblich",
    "weich",
    "weil",
    "wein",
    "weinen",
    "weit",
    "weiter",
    "weitermachen",
    "weiterhelfen",
    "welcher",
    "welt",
    "wenig",
    "wenigst",
    "werden",
    "werkstatt",
    "wettbewerb",
    "wetter",
    "wichtig",
    "wieder",
    "wiederholen",
    "wiederhören",
    "wiedersehen",
    "willkommen",
    "wind",
    "windig",
    "wirklich",
    "wissen",
    "weiß",
    "witz",
    "witzig",
    "wohnen",
    "wohnung",
    "wohnzimmer",
    "wolke",
    "wollen",
    "wille",
    "wort",
    "wunderbar",
    "wunsch",
    "wünschen",
    "wurst",
]

GrundwortschatzZ = [
    "zahl",
    "zahlen",
    "zahn",
    "zeichnen",
    "zeigen",
    "zeit",
    "zeitschrift",
    "zeitung",
    "zelt",
    "zentrum",
    "zettel",
    "zeugnis",
    "ziehen",
    "ziel",
    "zimmer",
    "zirkus",
    "zitrone",
    "zoo",
    "zucker",
    "zuerst",
    "zufrieden",
    "zug",
    "zuhören",
    "zumachen",
    "zurück",
    "zurückfahren",
    "zurückgeben",
    "zurückgehen",
    "zurückkommen",
    "zurücklaufen",
    "zusammen",
    "zwischen",
]

#print(len(GrundwortschatzA))
#print(''.join([str(GrundwortschatzA[(random.randint(41, 80))]), str(GrundwortschatzA[(random.randint(1, 40))])]).capitalize())

GanzerGrundwortschatz = GrundwortschatzA + GrundwortschatzB + GrundwortschatzC + GrundwortschatzD + GrundwortschatzE + GrundwortschatzF + GrundwortschatzG + GrundwortschatzH + GrundwortschatzI + GrundwortschatzJ + GrundwortschatzK + GrundwortschatzL + GrundwortschatzM + GrundwortschatzN + GrundwortschatzO +GrundwortschatzP +GrundwortschatzQ + GrundwortschatzR +GrundwortschatzS +GrundwortschatzT +GrundwortschatzU +GrundwortschatzV + GrundwortschatzW + GrundwortschatzZ

def GanzeKombinatorik(Liste):
    Liste2 = Liste
    Neueliste = []
    for Stelle in Liste:
        for Stelle2 in Liste2:
            Neueliste.append((Stelle +Stelle2))
        print(random.sample(Neueliste, len(Neueliste)))
        #Sample zweiter Value wie viel der liste genommen werden soll zur generierten rückgabe einer durcheinanderrgebrachten liste.
        print(len(Neueliste))
    return Neueliste


Dateikombinatorik = open("kombinatorikliste.py", "w")

Dateikombinatorik.write(json.dumps(GanzeKombinatorik(GanzerGrundwortschatz)))
#print(''.join([str(GrundwortschatzA[(random.randint(41, 80))]), str(GrundwortschatzA[(random.randint(1, 40))])]).capitalize())












#print("!Es gilt dies im Nutzerverzeichnis laufen zu lassen.")
#Daten:

#GrundwortschatzFamilienmitglieder =["bruder","cousin","cousinen","eltern","enkel","enkelinnen","geschwister","großeltern","großmutter","oma","großvater","opa","kind","mutter","onkel","schwester","sohn","tante","tochter","vater","papa","verwandten"]

#GrundwortschatzAnweisungssprachezurPrüfung = ["antwortbogen","aufgaben","beispiel","durchsagen","lösung","markieren","prüfer","prüferinnen","prüfung","punkt","teil","test","text","wörterbuch"]

#GrundwortschatzFamilienstand =
#["ledigen","verheirateten","getrennten","geschiedenen"]

#GrundwortschatzFarben =
#["blau","braun","gelb","grau","grün","lila","orange","rosa","rot","schwarz","weiß"]

#GrundwortschatzBerufe =
#["angestellten","angestelltinnen","arzt","ärztinnen","auszubildenden","auszubildendinnen", "autor", "autorinnen", "bäcker", "bäckerinnen", "doktor", "doktorinnen", "fahrer", "fahrerinnen", "friseur", "friseurinnen", "handwerker", "handwerkerinnen", "hausmann", "hausfrau", "journalist", "journalistinnen", "kaufmann", "kaufleute", "kauffrau", "kellner", "kellnerinnen", "koch", "köchinnen", "krankenpfleger", "krankenschwester", "künstler", "künstlerinnen", "lehrer", "lehrerinnen", "mechaniker", "mechanikerinnen", "model", "musiker", "musikerinnen", "polizist", "polizistinnen", "rentner", "rentnerinnen", "sänger", "sängerinnen", "schauspieler", "schauspielerinnen",
#"techniker", "technikerinnen",
#"verkäufer", "verkäuferinnen"]

#GrundwortschatzHimmelsrichtungen =
#["norden","süden","osten","westen"]

#GrundwortschatzLänderundNationalitäten =
#["deutschland", "deutsche", "deutsch", "österreich", "österreicher", "österreicherinnen", "österreichisch", "schweiz", "schweizer", "schweizerinnen", "schweizerisch", "luxemburg", "luxemburger", "luxemburgerinnen","luxemburgisch", "europa", "europäer", "europäerinnen", "europäisch"]

#GrundwortschatzSchuleundSchüler =
#["Abitur" (Sg.)
#"Direktor", -en
#"Hausaufgabe", -n
#"Klasse", -n
#"Klassenfahrt", -en
#"Sekretariat", -e
#"Stundenplan",  ̈-e
#"Biologie"
#"Chemie"
#"Deutsch"
#"Englisch"
#"Französisch"
#"Geografie"
#"Geschichte"
#"Kunst(erziehung)"
#"Latein"
#"Mathematik"
#"Musik"
#"Physik"
#"Religion"
#"Sozialkunde"
#"Sport"]

#GrundwortschatzFeiertage =
#["Karneval"
#"Ostern"
#"Weihnachten""
#"Neujahr"/"Silvester""]

#GrundwortschatzJahreszeiten =
#["Frühling / Frühjahr"
#"Sommer"
#"Herbst"
#"Winter"]

#GrundwortschatzMonate=
#["Januar"
#"Februar"
#"März"
#"April"
#"Mai"
#"Juni"
#"Juli"
#"August"
#"September"
#"Oktober"
#"November"
#"Dezember"]

#GrundwotschatzTageszeiten =
#["Tag", -e
#"Morgen", -
#"Vormittag", -e
#"Mittag", -e
#"Nachmittag", -e
#"Abend", -e
#"Nacht",  ̈ –e
#"Mitternacht"
#täglich, "tagsüber"
#morgens, am "Morgen"
#vormittags, am "Vormittag"
#mittags, am "Mittag"
#nachmittags, am "Nachmittag"
#abends, am "Abend"
#nachts, in der "Nacht"
#um "Mitternacht"]

#Grundwortschatzwochentage =
#[am Wochenende
#montags, am "Montag"
#dienstags, am "Dienstag"
#,"Mittwoch","Donnerstag","Freitag","Samstag","Sonntag","Arbeitstag","Werktag","Feiertag"]

#GrundwortschatzZeitmaße = ["Sekunde","Minute","Stunde","Woche","Jahr"]
